# Generated by Django 5.1.2 on 2024-11-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_students_delete_studentnames_item_studentusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='studentUsers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
