# Generated by Django 5.1.2 on 2024-12-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_alter_item_studentusers_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
